### ISSUE TITLE
Facing PlatformException(SendMediaError) error

### ISSUE THREAD

**Issue by ghost** [mingchaogui/SnapkitFlutter#2]
Facing this error
I/flutter (26140): PlatformException(SendMediaError, lateinit property mediaFactory has not been initialized, kotlin.UninitializedPropertyAccessException: lateinit property mediaFactory has not been initialized
I/flutter (26140): 	at com.mintinglabs.snapkit_flutter_android.SnapkitFlutterAndroidPlugin.send(SnapkitFlutterAndroidPlugin.kt:107)
I/flutter (26140): 	at com.mintinglabs.snapkit_flutter_android.SnapkitFlutterAndroidPlugin.onMethodCall(SnapkitFlutterAndroidPlugin.kt:78)
I/flutter (26140): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
I/flutter (26140): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
I/flutter (26140): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
I/flutter (26140): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
I/flutter (26140): 	at android.os.Handler.handleCallback(Handler.java:942)
I/flutter (26140): 	at android.os.Handler.dispatchMessage(Handler.java:99)
I/flutter (26140): 	at android.os.Looper.loopOnce(Looper.ja
I/flutter (26140): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651:7)
I/flutter (26140): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:322:18)
I/flutter (26140): <asynchronous suspension>

**Comment by goops17** [comment]
Were you able to solve the issue?
